import 'package:flutter/material.dart';

class Global {
  static List music = [
    {
      'audio': 'assets/audio/music.mp3',
      'image': 'assets/image/image.jpg',
      'title': 'Jaane Na Dunga Kahi',
      'subtitle': 'Armaan Malik',
      'color': Colors.blue.shade600,
    },
    {
      'audio': 'assets/audio/music1.mp3',
      'image': 'assets/image/image1.jpg',
      'title': 'Deva Deva',
      'subtitle': 'Arijit Singh',
      'color': Colors.blue.shade400,
    },
    {
      'audio': 'assets/audio/music2.mp3',
      'image': 'assets/image/image2.jpg',
      'title': 'Aaj Sajeya',
      'subtitle': 'Punit Malhotra',
      'color': Colors.blue.shade300,
    },
    {
      'audio': 'assets/audio/music3.mp3',
      'image': 'assets/image/image3.jpg',
      'title': 'Tum Prem Ho',
      'subtitle': 'Mohit Lalwani',
      'color': Colors.green.shade600,
    },
    {
      'audio': 'assets/audio/music4.mp3',
      'image': 'assets/image/image4.jpg',
      'title': 'Apna Bana Le',
      'subtitle': 'Arijit Singh',
      'color': Colors.green.shade400,
    },
    {
      'audio': 'assets/audio/music5.mp3',
      'image': 'assets/image/image5.jpg',
      'title': 'Rangisari',
      'subtitle': 'Kanishk & Kavita',
      'color': Colors.green.shade300,
    },
    {
      'audio': 'assets/audio/music6.mp3',
      'image': 'assets/image/image6.jpg',
      'title': 'Barrish',
      'subtitle': 'Kunaal V',
      'color': Colors.yellow.shade600,
    },
    {
      'audio': 'assets/audio/music7.mp3',
      'image': 'assets/image/image8.jpg',
      'title': 'Dil Diyan Gallan',
      'subtitle': 'Vishal & Shekhar',
      'color': Colors.yellow.shade400,
    },
    {
      'audio': 'assets/audio/music8.mp3',
      'image': 'assets/image/image7.jpg',
      'title': 'Dhun Lagi ',
      'subtitle': 'Siddharth Amit',
      'color': Colors.yellow.shade300,
    },
    {
      'audio': 'assets/audio/music9.mp3',
      'image': 'assets/image/image9.jpg',
      'title': 'Tere Mere',
      'subtitle': 'Neeti Mohan',
      'color': Colors.cyan.shade600,
    },
    {
      'audio': 'assets/audio/music10.mp3',
      'image': 'assets/image/image10.jpg',
      'title': 'Ak Zindgi',
      'subtitle': 'Tanishkaa',
      'color': Colors.cyan.shade400,
    },
    {
      'audio': 'assets/audio/music11.mp3',
      'image': 'assets/image/image11.jpg',
      'title': 'Tum Se Hi',
      'subtitle': 'Mohit Chauhan',
      'color': Colors.cyan.shade200,
    },
    {
      'audio': 'assets/audio/music12.mp3',
      'image': 'assets/image/image12.jpg',
      'title': 'Baato Ko Teri',
      'subtitle': 'Arijit Singh',
      'color': Colors.red.shade600,
    },
    {
      'audio': 'assets/audio/music13.mp3',
      'image': 'assets/image/image13.jpg',
      'title': 'Joome Jo Pathaan',
      'subtitle': 'Arijit Singh',
      'color': Colors.red.shade400,
    },
    {
      'audio': 'assets/audio/music14.mp3',
      'image': 'assets/image/image14.jpg',
      'title': 'Bulleya',
      'subtitle': 'Vishal & Shekhar',
      'color': Colors.red.shade300,
    },
    {
      'audio': 'assets/audio/music15.mp3',
      'image': 'assets/image/image15.jpg',
      'title': 'Zindgi',
      'subtitle': 'Jubin Nautiyal ',
      'color': Colors.purple.shade600,
    },
    {
      'audio': 'assets/audio/music16.mp3',
      'image': 'assets/image/image16.jpg',
      'title': 'Kise Muje Tum Mili',
      'subtitle': 'A.R. Rahman',
      'color': Colors.purple.shade400,
    },
    {
      'audio': 'assets/audio/music17.mp3',
      'image': 'assets/image/image17.jpg',
      'title': 'Maiyya Mainu',
      'subtitle': 'Sachet-Parampara',
      'color': Colors.purple.shade300,
    },
    {
      'audio': 'assets/audio/music18.mp3',
      'image': 'assets/image/image18.jpg',
      'title': 'Raataan Lambiyan',
      'subtitle': 'Jubin Nautiyal ',
      'color': Colors.pink.shade600,
    },
    {
      'audio': 'assets/audio/music19.mp3',
      'image': 'assets/image/image19.jpg',
      'title': 'Bewajah',
      'subtitle': 'Arijit Singh',
      'color': Colors.pink.shade400,
    },
    {
      'audio': 'assets/audio/music20.mp3',
      'image': 'assets/image/image20.jpg',
      'title': 'Saiyaara',
      'subtitle': 'Mohit Chauhan',
      'color': Colors.pink.shade300,
    },
    {
      'audio': 'assets/audio/music21.mp3',
      'image': 'assets/image/image21.jpg',
      'title': 'Lime juice...',
      'subtitle': 'Lata Mangeshkar',
      'color': Colors.teal.shade600,
    },
    {
      'audio': 'assets/audio/music22.mp3',
      'image': 'assets/image/image22.jpg',
      'title': 'Gode Pe Sawar',
      'subtitle': 'Triptii Dimri',
      'color': Colors.teal.shade400,
    },
    {
      'audio': 'assets/audio/music23.mp3',
      'image': 'assets/image/image23.jpg',
      'title': 'Rasiya',
      'subtitle': 'Amitabh',
      'color': Colors.teal.shade300,
    },
    {
      'audio': 'assets/audio/music24.mp3',
      'image': 'assets/image/image24.jpg',
      'title': 'Uda Ja Kale Kawa',
      'subtitle': 'Vicky Singh',
      'color': Colors.orange.shade600,
    },
    {
      'audio': 'assets/audio/music25.mp3',
      'image': 'assets/image/image25.jpg',
      'title': 'Jab Bhi Teri Yaad',
      'subtitle': 'I-SHOJ',
      'color': Colors.orange.shade400,
    },
    {
      'audio': 'assets/audio/music26.mp3',
      'image': 'assets/image/image26.jpg',
      'title': 'Tera Bina',
      'subtitle': 'Mustafa Zahid',
      'color': Colors.orange.shade300,
    },
  ];
}
